# Generated by Django 6.0.1 on 2026-01-28 10:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel'), ('staff', 'Staff Quarters')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels_in_charge', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('single', 'Single (1 bed)'), ('double', 'Double (2 beds)'), ('triple', 'Triple (3 beds)'), ('dormitory', 'Dormitory (4+ beds)')], default='double', max_length=20)),
                ('bed_count', models.PositiveIntegerField(default=2)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('has_attached_bathroom', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_wardrobe', models.BooleanField(default=True)),
                ('has_study_table', models.BooleanField(default=True)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'verbose_name': 'Hostel Room',
                'verbose_name_plural': 'Hostel Rooms',
                'db_table': 'hostel_rooms',
                'ordering': ['hostel', 'floor', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.PositiveIntegerField(blank=True, null=True)),
                ('allocation_date', models.DateField()),
                ('vacating_date', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelroom')),
            ],
            options={
                'verbose_name': 'Hostel Allocation',
                'verbose_name_plural': 'Hostel Allocations',
                'db_table': 'hostel_allocations',
                'ordering': ['-allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='HostelVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('visit_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hostel_visits', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_visitors', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Visitor',
                'verbose_name_plural': 'Hostel Visitors',
                'db_table': 'hostel_visitors',
                'ordering': ['-visit_date', '-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='LeavePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('day_outing', 'Day Outing'), ('overnight', 'Overnight Leave'), ('weekend', 'Weekend Leave'), ('holiday', 'Holiday Leave'), ('emergency', 'Emergency Leave')], max_length=20)),
                ('from_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
                ('destination', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_time', models.TimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_passes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_passes', to='students.student')),
            ],
            options={
                'verbose_name': 'Leave Pass',
                'verbose_name_plural': 'Leave Passes',
                'db_table': 'hostel_leave_passes',
                'ordering': ['-from_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=20)),
                ('menu_items', models.TextField(help_text='List of items for this meal')),
                ('timing', models.CharField(blank=True, help_text='e.g., 7:30 AM - 9:00 AM', max_length=50)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_menus', to='hostel.hostel')),
            ],
            options={
                'verbose_name': 'Mess Menu',
                'verbose_name_plural': 'Mess Menus',
                'db_table': 'mess_menus',
                'ordering': ['hostel', 'day', 'meal_type'],
                'unique_together': {('hostel', 'day', 'meal_type')},
            },
        ),
    ]
