# Generated by Django 5.2.10 on 2026-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A, B, C', max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(default=40, help_text='Maximum students allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
                'ordering': ['standard__numeric_value', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Class 1, Class 10, KG', max_length=50)),
                ('numeric_value', models.PositiveIntegerField(help_text='Numeric order for sorting (0 for KG, 1-12 for classes)')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class/Standard',
                'verbose_name_plural': 'Classes/Standards',
                'db_table': 'standards',
                'ordering': ['numeric_value'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Subject code e.g., MATH101', max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('both', 'Theory + Practical')], default='theory', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('max_theory_marks', models.PositiveIntegerField(default=100)),
                ('max_practical_marks', models.PositiveIntegerField(default=0)),
                ('passing_percentage', models.PositiveIntegerField(default=33)),
                ('is_optional', models.BooleanField(default=False, help_text='Is this an optional/elective subject?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
    ]
