# Generated by Django 5.2.10 on 2026-01-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.standard'),
        ),
        migrations.AddField(
            model_name='subject',
            name='standards',
            field=models.ManyToManyField(blank=True, help_text='Classes where this subject is taught', related_name='subjects', to='academics.standard'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('standard', 'name')},
        ),
    ]
