# Generated by Django 5.2.10 on 2026-01-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='Unique admission/registration number', max_length=20, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('aadhaar_number', models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12)),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC (Other Backward Class)'), ('sc', 'SC (Scheduled Caste)'), ('st', 'ST (Scheduled Tribe)'), ('ews', 'EWS (Economically Weaker Section)')], default='general', max_length=10)),
                ('religion', models.CharField(blank=True, choices=[('hinduism', 'Hinduism'), ('islam', 'Islam'), ('christianity', 'Christianity'), ('sikhism', 'Sikhism'), ('buddhism', 'Buddhism'), ('jainism', 'Jainism'), ('other', 'Other')], max_length=20)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('sub_caste', models.CharField(blank=True, max_length=100)),
                ('mother_tongue', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DL', 'Delhi'), ('DN', 'Dadra and Nagar Haveli and Daman & Diu'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2)),
                ('pincode', models.CharField(max_length=6)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone', models.CharField(blank=True, max_length=15)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_qualification', models.CharField(blank=True, max_length=100)),
                ('father_annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('father_aadhaar', models.CharField(blank=True, max_length=12)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=15)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_qualification', models.CharField(blank=True, max_length=100)),
                ('mother_aadhaar', models.CharField(blank=True, max_length=12)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('guardian_address', models.TextField(blank=True)),
                ('admission_date', models.DateField()),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('tc_number', models.CharField(blank=True, help_text='Transfer Certificate number from previous school', max_length=50)),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rte', models.BooleanField(default=False, help_text='RTE (Right to Education) admission')),
                ('has_transport', models.BooleanField(default=False)),
                ('has_hostel', models.BooleanField(default=False)),
                ('has_scholarship', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_class', models.ForeignKey(blank=True, help_text='Class at the time of admission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='academics.standard')),
                ('current_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['current_section', 'roll_number', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('aadhaar', 'Aadhaar Card'), ('tc', 'Transfer Certificate'), ('cc', 'Character Certificate'), ('caste', 'Caste Certificate'), ('income', 'Income Certificate'), ('marksheet', 'Previous Marksheet'), ('photo', 'Passport Photo'), ('other', 'Other Document')], max_length=20)),
                ('document_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='students/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'db_table': 'student_documents',
            },
        ),
    ]
